# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('docsis', ['network', 'applications'])
    module.source = [
        'model/docsis.cc',
        'model/hfc.cc',
        'model/cm-device.cc',
        'model/cmts-device.cc',
        'model/docsis-header.cc',
        'helper/docsis-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('docsis')
    module_test.source = [
        'test/docsis-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'docsis'
    headers.source = [
        'model/docsis.h',
        'model/hfc.h',
        'model/cm-device.h',
        'model/cmts-device.h',
        'model/docsis-enums.h',
        'model/docsis-header.h',
        'helper/docsis-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

